name: Round checkbox

description: Developer blog about me (Aaron Junker)

avatar: https://i.imgur.com/xM91AaW.png

footer-links:
  email: aaron.junker@outlook.com 
  github: aaron-junker
  twitter: theredcuber
  youtube: channel/UC4PrjxDrZ_PCqhnzBfjQxdQ
  linkedin: aaron-junker
  stackoverflow: users/14774889/aaron-junker
  instagram: aaronjunkerpublic/
  mastodon: phpc.social/@aaronJunker
  
url: https://blog.aaron-junker.ch

baseurl: ""

# Disqus flag
disqus: roundcheckbox

permalink: "/:title"

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

sass:
  style: expanded 

gems:
  - jekyll-sitemap 
  - jekyll-feed 

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

collections:
  projects:
    output: true
    permalink: /:collection/:name
