#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Round checkbox

# Short bio or description (displayed in the header)
description: Developer blog about me (Aaron Junker)

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://i.imgur.com/xM91AaW.png
#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  email: aaron.junker@outlook.com 
  github: aaron-junker
  twitter: theredcuber
  youtube: channel/UC4PrjxDrZ_PCqhnzBfjQxdQ
  linkedin: aaron-junker
  stackoverflow: users/14774889/aaron-junker
  instagram: aaronjunkerpublic/
  mastodon: php.social/aaronJunker
  

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: https://blog.aaron-junker.ch

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

# Disqus flag
disqus: roundcheckbox

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

collections:
  projects:
    output: true
    permalink: /:collection/:name
