name: "dadas"
description: "adasdasd"
body:
- type: input
  id: dasd
  attributes:
    label: "dasd"
  validations:
    required: false
- type: markdown
  attributes:
    value: |
      dsads
      da
      
      
      da
      
      
      dasds
      
      adsads
      
      
- type: textarea
  attributes:
    label: "dasdsa"
    description: "asdd"
    placeholder: |
      dasd
      da
      sd
      asd
  validations:
    required: false
- type: dropdown
  id: dasds
  attributes:
    label: "dsads"
    multiple: true
    options: 
      - Option 1
      - Option 2
  validations:
    required: true
- type: checkboxes
  id: asd
  attributes:
    label: "davbsd"
    description: "dasd"
    options: 
      - label: "dasdr43rtsa"
        required: false
